version: "3.8"
services:
  loan-servicing-ui:
    build: 
      context: ./loan-servicing-ui
      dockerfile: dev.Dockerfile
    image: loan-servicing/ui
    ports:
      - "3000:3000"
    volumes:
      - "./loan-servicing-ui/src:/opt/app/src"
    environment:
      - PORT=3000
      - NODE_ENV=development
      - API_URL=http://loan-servicing-api:3001
  loan-servicing-api:
    build: 
      context: ./loan-servicing-api
      dockerfile: dev.Dockerfile
    image: loan-servicing/api
    ports:
      - "3001:3001"
    volumes:
      - "./loan-servicing-api/src:/opt/app/src"
    environment:
      - PORT=3001
      - NODE_ENV=development
