version: '3.8'
services:
  loan-servicing-db:
    build: ./libs/sql-db
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=AbC!2345
      - DB_NAME=LoanServicing
    ports:
      - '1433:1433'
    healthcheck: # Ensures the DB is active before starting the API
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P 'AbC!2345' -Q 'select 1;'
      start_period: '30s'
      start_interval: '1s'
    attach: false
    volumes:
      - ./libs/sql-db/data:/var/opt/mssql/data
  loan-servicing-ui:
    depends_on:
      - loan-servicing-api
    build:
      context: .
      dockerfile: ./packages/loan-servicing-ui/dev.Dockerfile
    image: loan-servicing/ui
    ports:
      - '3000:3000'
      - '35729:35729' # Live reload server port
    volumes:
      - './packages/loan-servicing-ui/src:/opt/app/packages/loan-servicing-ui/src:ro'
      - ./libs:/opt/app/libs:ro
    environment:
      - PORT=3000
      - NODE_ENV=development
      - NODE_PATH=src
      - API_URL=http://loan-servicing-api:3001
  loan-servicing-api:
    depends_on:
      loan-servicing-db:
        condition: service_healthy
    build:
      context: .
      dockerfile: ./packages/loan-servicing-api/dev.Dockerfile
    image: loan-servicing/api
    ports:
      - '3001:3001'
    volumes:
      - ./packages/loan-servicing-api/src:/opt/app/packages/loan-servicing-api/src:ro
      - ./libs:/opt/app/libs:ro
    environment:
      - PORT=3001
      - NODE_ENV=development
      - NODE_PATH=src
      - SQL_DB_HOST=loan-servicing-db
      - SQL_DB_PORT=1433
