version: '3.8'
services:
  loan-servicing-db:
    build: ./libs/sql-db
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=AbC!2345
      - DB_NAME=LoanServicing
    ports:
      - '1433:1433'
    healthcheck: # Ensures the DB is active before starting the API
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P 'AbC!2345' -Q 'select 1;'
      start_period: '60s'
      start_interval: '1s'
    attach: false
  loan-servicing-ui:
    depends_on:
      - loan-servicing-api
    build:
      context: .
      dockerfile: ./packages/loan-servicing-ui/dev.Dockerfile
    image: loan-servicing/ui
    ports:
      - '3000:3000'
      - '35729:35729' # Live reload server port
      - '5959:5959' # Debugger port
    volumes:
      - './packages/loan-servicing-ui/src:/opt/app/packages/loan-servicing-ui/src:ro'
      - './packages/loan-servicing-ui/public:/opt/app/packages/loan-servicing-ui/public:ro'
      - ./libs:/opt/app/libs:ro
    environment:
      - PORT=3000
      - NODE_ENV=development
      - NODE_PATH=src
      - API_URL=http://loan-servicing-api:3001
      - FUNCTIONS_URL=http://loan-servicing-functions
      - DEV_MODE=true
  loan-servicing-api:
    depends_on:
      loan-servicing-db:
        condition: service_healthy
    build:
      context: .
      dockerfile: ./packages/loan-servicing-api/dev.Dockerfile
    image: loan-servicing/api
    ports:
      - '3001:3001'
      - '5858:5858' # Debugger port
    volumes:
      - ./packages/loan-servicing-api/src:/opt/app/packages/loan-servicing-api/src:ro
      - ./libs:/opt/app/libs:ro
    environment:
      - PORT=3001
      - NODE_ENV=development
      - NODE_PATH=src
      - SQL_DB_HOST=loan-servicing-db
      - SQL_DB_PORT=1433
      - SQL_DB_PASSWORD=AbC!2345
      - SQL_DB_USER=sa
      - SQL_DB_NAME=LoanServicing
      - UI_URL=http://localhost:3000 # This is used to build links so uses the external docker port URL
  dev-azurite:
    image: 'mcr.microsoft.com/azure-storage/azurite:latest'
    attach: false
    ports:
      - 10000:10000
      - 10001:10001
      - 10002:10002
  loan-servicing-functions:
    build:
      context: .
      dockerfile: ./packages/loan-servicing-functions/Dockerfile
    ports:
      - 3002:80
    environment:
      # Copy .env variables through to container
      - AzureWebJobsStorage="UseDevelopmentStorage=true"
      - StorageConnectionString
      - AzureWebJobsStorageConnectionString
      - SLACK_WEBHOOK_URL
      - ApiUrl=http://loan-servicing-api:3001
    depends_on:
      - dev-azurite
    volumes:
      - ./packages/loan-servicing-functions:/home/site/wwwroot/packages/loan-servicing-functions
      - ./libs:/home/site/wwwroot/libs:ro
