# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Deploy Prototype

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install CLI tools
        run: |
          npm install -g typescript
          npm install -g @nestjs/cli

      - name: Build All Applications
        run: |
          npm install
          npm run build --workspaces

      - name: Install locally for UI package
        working-directory: ./packages/loan-servicing-ui
        run: |
          npm install --workspaces=false --install-links

      - name: Install locally for API package
        working-directory: ./packages/loan-servicing-api
        run: |
          npm install --workspaces=false --install-links

      - name: Install locally for Functions package
        working-directory: ./packages/loan-servicing-functions
        run: |
          npm install --workspaces=false --install-links

      - name: Zip artifact for UI Server
        working-directory: ./packages/loan-servicing-ui
        run: zip ui-release.zip . -r

      - name: Zip artifact for API Server
        working-directory: ./packages/loan-servicing-api
        run: zip api-release.zip . -r

      - name: Zip artifact for Functions
        working-directory: ./packages/loan-servicing-functions
        run: zip functions-release.zip . -r

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: applications
          path: |
            ./packages/loan-servicing-ui/ui-release.zip
            ./packages/loan-servicing-api/api-release.zip
            ./packages/loan-servicing-functions/functions-release.zip

  deploy-functions:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: applications

      - name: Unzip artifact for deployment
        run: unzip loan-servicing-functions/functions-release.zip

      - name: 'Deploy Function App'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: 'ls-prototype-functions'
          slot-name: 'Production'
          package: '.'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_FEBC8422814E464F991031FB86A3CA35 }}


  deploy-api:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-api-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: applications

      - name: Unzip artifact for deployment
        run: unzip loan-servicing-api/api-release.zip

      - name: 'Deploy API Server'
        id: deploy-to-api-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'ls-prototype-api'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_56EC5F10C04A4E5D8C81807F33DF0203 }}

  deploy-ui:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-ui-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: applications

      - name: Unzip artifact for deployment
        run: unzip loan-servicing-ui/ui-release.zip

      - name: 'Deploy UI Server'
        id: deploy-to-ui-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'ls-prototype-ui'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_6AA768B1CF8E460FB637F8F683E05484 }}
